### ISSUE TITLE
repo management overall is broke 

### ISSUE THREAD

**Issue by Maddieisme** [sbingner/Sileo#2]
title pretty much says it all. expected behavior is you swipe left to remove, or at least press edit and have a remove button next to the repo icons. instead, neither of these happen. 
edit:
seems like repo management in sileo is broken overall. refreshing sources makes it get stuck in a loop.

**Comment by sbingner** [comment]
You can manage repos added in sileo from sileo.  If you added it from cydia, you need to remove it from cydia.
